name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      id: prepareArtifact
      run: |
        ./gradlew assembleRelease
        find ${{github.workspace}}/app -name "*.apk"
        releaseName=`ls app/build/outputs/apk/release/*.apk | awk -F '(/|.zip)' '{print $3}'` && echo "releaseName=$releaseName" >> $GITHUB_OUTPUT

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: ${{ steps.prepareArtifact.outputs.releaseName }}
        path: ${{github.workspace}}/app/build/outputs/apk/release/*.apk
