name: Android Release CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # 例如: v1.0, v1.0.0, v1.0.0-beta
  workflow_dispatch: # 允许手动触发

jobs:
  build_and_release:
    name: Build and Release Signed APK
    runs-on: ubuntu-latest
    permissions:
      contents: write # 创建 Release 和上传附件所必需的权限

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode Keystore and Set up Signing
      id: setup_signing
      # 仅当所有签名相关的 Secrets 都已设置时才运行此步骤
      if: ${{ secrets.SIGNING_KEY_STORE_BASE64 && secrets.SIGNING_STORE_PASSWORD && secrets.SIGNING_KEY_ALIAS && secrets.SIGNING_KEY_PASSWORD }}
      run: |
        echo "Decoding keystore..."
        # 定义解码后密钥库文件的存放路径
        store_file_path="${{ runner.temp }}/keystore.jks"
        
        # 将 Base64 编码的 Secret 解码并写入文件
        echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 --decode > "$store_file_path"
        
        # 检查文件是否成功创建
        if [ -f "$store_file_path" ]; then
          echo "Keystore file created successfully."
          # 将文件路径和启用标志作为输出，供后续步骤使用
          echo "store_file=$store_file_path" >> $GITHUB_OUTPUT
          echo "signing_enabled=true" >> $GITHUB_OUTPUT
        else
          echo "::error::Keystore file could not be created from the secret."
          exit 1
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Signed APK and gather info
      id: build_apk
      # 将签名凭据作为环境变量传递给 Gradle
      # Gradle 会在 assembleRelease 任务中自动使用这些变量（如果 build.gradle 已正确配置）
      env:
        SIGNING_STORE_FILE: ${{ steps.setup_signing.outputs.store_file }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      run: |
        # 如果 Gradle 配置正确，此命令现在将生成一个已签名的 APK
        ./gradlew assembleRelease
        echo "APK build process completed."
        
        apk_dir="app/build/outputs/apk/release"
        echo "apk_directory_path=$apk_dir" >> $GITHUB_OUTPUT
        
        first_apk_path=$(find "$apk_dir" -name "*.apk" -type f -print -quit)
        
        if [ -n "$first_apk_path" ]; then
          apk_filename=$(basename "$first_apk_path")
          echo "apk_name_example=$apk_filename" >> $GITHUB_OUTPUT
          echo "Found example APK: $apk_filename"
        else
          echo "::warning::No APK file found in $apk_dir."
          echo "apk_name_example=" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2.0.6
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          Automated signed release for version ${{ github.ref_name }}.
          ${{ steps.build_apk.outputs.apk_name_example && format('APK: {0}', steps.build_apk.outputs.apk_name_example) || 'The signed APK is attached as an asset below.' }}
          
          All built APKs from the `${{ steps.build_apk.outputs.apk_directory_path }}` directory are included.
        files: |
          ${{ steps.build_apk.outputs.apk_directory_path }}/*.apk
          app/build/outputs/mapping/release/mapping.txt # 同时上传 ProGuard/R8 的 mapping 文件，非常重要！
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
